export const SECTIONS = [
  { key: "hero", label: "홈 · 첫 화면 소개" },
  { key: "thesis", label: "홈 · 논문" },
  { key: "recommendation", label: "홈 · 추천사" },
  { key: "advisoryBoard", label: "홈 · 자문위원" },
  { key: "videos", label: "홈 · 영상" },
  { key: "culturalRespect", label: "홈 · 감사 문구" },
  { key: "contact", label: "홈 · 연락처" },
  { key: "program", label: "프로그램" },
  { key: "research", label: "연구/출판" },
  { key: "workshops", label: "워크숍" },
  { key: "performances", label: "공연" },
  { key: "nav", label: "공통 · 메뉴 이름" },
  { key: "footer", label: "공통 · 푸터" },
];

export const LABELS = {
  eyebrow: "작은 라벨 (제목 위 영문)",
  heading: "제목",
  title: "제목",
  description: "설명",
  summary: "요약",
  name: "이름",
  role: "직함",
  bio: "소개글",
  philosophy: "철학 문구",
  photo: "사진",
  image: "사진",
  images: "사진",
  items: "항목",
  videos: "영상 목록",
  intro: "소개글",
  link: "링크",
  label: "링크 문구",
  href: "링크 주소",
  alt: "사진 설명 (화면에 보이지 않음)",
  cta: "버튼 문구",
  applyLabel: "신청 버튼 문구",
  applyHref: "신청 링크 주소",
  paragraphs: "본문 (영문)",
  paragraphsKo: "본문 (한국어 번역)",
  noteKo: "안내 문구 (한국어)",
  headingKo: "소제목 (한국어)",
  nameKo: "이름 (한국어)",
  titleKo: "직함 (한국어)",
  affiliationKo: "소속 (한국어)",
  affiliation: "소속",
  letters: "추천사 목록",
  members: "자문위원 목록",
  linesEn: "영문 정보 (첫 줄은 이름)",
  linesKo: "한국어 정보",
  captionBelow: "설명을 사진 아래에 배치",
  email: "이메일",
  instagramHandle: "인스타그램 아이디",
  instagramUrl: "인스타그램 링크",
  copyright: "저작권 문구",
  programs: "프로그램 목록",
  format: "진행 형식",
  experience: "경험 내용",
  approach: "프로그램 접근 방식",
  musicTherapyTitle: "음악치료 소제목",
  musicTherapyBody: "음악치료 본문",
  humanisticTitle: "인본주의 소제목",
  humanisticBody: "인본주의 본문",
  highlight: "대표 프로그램 소개",
  testimonials: "참가자 경험",
  quotes: "후기 문장",
  en: "영어",
  ko: "한국어",
  location: "지역",
  number: "번호",
  reversed: "한국어를 먼저 보여주기",
  writing: "Medium 글 영역",
  titleEn: "제목 (영문)",
  bodyEn: "본문 (영문)",
  bodyKo: "본문 (한국어)",
  toggleLabel: "언어 전환 버튼 글자",
  home: "소개 메뉴",
  program: "프로그램 메뉴",
  research: "연구/출판 메뉴",
  workshops: "워크숍 메뉴",
  performances: "공연 메뉴",
};

export const HINTS = {
  bio: "굵게 표시하려면 **이렇게** 별표 두 개로 감싸세요.",
  musicTherapyBody: "굵게 표시하려면 **이렇게** 별표 두 개로 감싸세요.",
  humanisticBody: "굵게 표시하려면 **이렇게** 별표 두 개로 감싸세요.",
  href: "https:// 로 시작하는 전체 주소를 넣어주세요.",
  applyHref: "구글폼 등 신청 링크를 넣어주세요.",
};

export const HIDDEN_PATHS = new Set(["lang", "hero.meta"]);

export const labelFor = (key) => LABELS[key] || key;
